DROP EVENT IF EXISTS ProcesarAsistenciasCada2Minutos;

DELIMITER //

CREATE EVENT IF NOT EXISTS ProcesarAsistenciasCada2Minutos
ON SCHEDULE EVERY 2 MINUTE
STARTS TIMESTAMPADD(MINUTE, -3 * 60, CURRENT_TIMESTAMP) -- Ajusta al UTC-3
DO
BEGIN
    CALL UBASISTENCIADB.ProcesarTodasAsistencias();
END;

//

DELIMITER ;