DROP EVENT IF EXISTS MarcarFaltasDiarias;

DELIMITER //
CREATE EVENT IF NOT EXISTS `MarcarFaltasDiarias`
ON SCHEDULE EVERY 1 DAY
STARTS TIMESTAMPADD(MINUTE, -3 * 60, CURRENT_TIMESTAMP) -- Ajusta al UTC-3
DO
BEGIN
    CALL UBASISTENCIADB.MarcarFaltas(NULL);
END

//

DELIMITER ;